version: 0.2

env:
  variables:
    NODE_ENV: 'prod'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - corepack enable
      - yarn -v
      - yarn
  pre_build:
    commands:
      - echo Generating Prisma client...
      - yarn prisma:generate
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Deploying migrations...
      - echo Build completed on `date`

artifacts:
  files:
    - dist/**/*
    - package-lock.json
    - package.json
    - yarn.lock
    - prisma/**/*
    - node_modules/**/*
