-- AlterTable
ALTER TABLE `Event` MODIFY `type` ENUM('PAY_WAITING', 'PAYED', 'PRODUCT_PREPARE', 'DELIVERING', 'DELIVERED', 'PURCHASE_CONFIRM', 'EXCHANGE', 'CANCEL', 'REFUND', 'CANCEL_NOPAY', 'REQUEST', 'CONFIRM', 'DONE', 'NOSHOW') NOT NULL;

-- AlterTable
ALTER TABLE `Order` MODIFY `status` ENUM('PAY_WAITING', 'PAYED', 'PRODUCT_PREPARE', 'DELIVERING', 'DELIVERED', 'PURCHASE_CONFIRM', 'EXCHANGE', 'CANCEL', 'REFUND', 'CANCEL_NOPAY', 'REQUEST', 'CONFIRM', 'DONE', 'NOSHOW') NOT NULL DEFAULT 'PAY_WAITING';

-- AlterTable
ALTER TABLE `OrderHistory` MODIFY `changedStatus` ENUM('PAY_WAITING', 'PAYED', 'PRODUCT_PREPARE', 'DELIVERING', 'DELIVERED', 'PURCHASE_CONFIRM', 'EXCHANGE', 'CANCEL', 'REFUND', 'CANCEL_NOPAY', 'REQUEST', 'CONFIRM', 'DONE', 'NOSHOW') NULL;
